### ISSUE TITLE
Difficulty Adjusting Toolbar Transparency in 'Beautiful Red Blur' Theme

### ISSUE THREAD

**Issue by elyeandre** [Godiesc/firefox-one#10]
![image](https://github.com/Godiesc/firefox-one/assets/96169920/d8ea477a-6603-400d-b0ff-6cdfd21afa2f)
![image](https://github.com/Godiesc/firefox-one/assets/96169920/3630c024-e0e5-40a6-ba22-a43db7ae46ce)
![image](https://github.com/Godiesc/firefox-one/assets/96169920/7cab5d62-9118-46ba-a1e4-af18963d224b)

I changed the background wallpaper according to the instructions. The theme I used is 'Beautiful Red Blur.' I like the theme because it makes the private tab transparent. Now, I've tried to pinpoint the location where I can change the transparency of the toolbar in CSS file, but it seems I can't find the exact location to change the transparency, like in the private tab

**Comment by Godiesc** [comment]
hi,
for the moment you can add this code after line 20  in `chrome/components/one_root-personal` and see if works, maybe this could be a feature in the next release. :) 

```
--lwt-private-image:  url("../images/newtab/private-dark.png") !important;                      
--lwt-header-image: url("../images/newtab/wallpaper-dark.png") !important; 
```

here is an example:
![imagen](https://github.com/Godiesc/firefox-one/assets/22057609/289f8789-7f4a-4eb5-a982-a005d734a4e3)

**Comment by elyeandre** [comment]
> hi, for the moment you can add this code after line 20 in `chrome/components/one_root-personal` and see if works, maybe this could be a feature in the next release. :)
> 
> ```
> --lwt-header-image: url("../images/newtab/wallpaper-dark.png") !important; 
> --lwt-additional-images: url("../images/newtab/wallpaper-dark.png") !important;
> ```
> 
> here is an example: ![imagen](https://user-images.githubusercontent.com/22057609/275690994-289f8789-7f4a-4eb5-a982-a005d734a4e3.png)

Thank you, it works
