### ISSUE TITLE
broken on fireox 120.0b1 windows11

### ISSUE THREAD

**Issue by lost22git** [Godiesc/firefox-one#11]
![Screenshot 2023-10-25 210830](https://github.com/Godiesc/firefox-one/assets/65008815/ab5fdd6e-62b1-41d9-82d1-d7afc9dee565)

**Comment by Godiesc** [comment]
thanks for the report, it seems firefox change the syntax for that preferences, in a few hours I'll make an update to the files, check it. :)

**Comment by lost22git** [comment]
@Godiesc 

it works very well, thanks a lot.

![Screenshot 2023-10-26 001208](https://github.com/Godiesc/firefox-one/assets/65008815/c50a92bc-1cad-4767-96e7-eadce9ae1bcc)
