### ISSUE TITLE
Persistent White Border

### ISSUE THREAD

**Issue by markrecabo** [Godiesc/firefox-one#12]
Hi,

Fan of the firefox-one but there was an white border persistent that i could not find the source coming from. I attached  the screenshot of it. 
![Screenshot 2023-10-27 190457](https://github.com/Godiesc/firefox-one/assets/47281377/0d5958d9-304a-4ecf-9c9b-9e63e9e1e974)

Device: Desktop
OS : Windows 11 Pro 22h2 latest build

**Comment by Godiesc** [comment]
hi, I use windows 10 and I don't see that problem, is not part of the theme, maybe is a windows 11 problem, you can see in the [preview section](https://github.com/Godiesc/firefox-one/tree/main/Previews) how the theme looks, are you tested in other PC?

**Comment by markrecabo** [comment]
Thanks for the quick reply! @Godiesc . Im pretty sure it is not on the them that I installed, because i changed it back to system theme or dark theme it still showing.

I guess I will have to try and run firefox with compatibility and get back to you!

**Comment by markrecabo** [comment]
Hi,

I think i found the problem! 

Before installing the latest update of Firefox-one. I was trying other firefoxcss and there was also compatibility issue (on windows 11) so i turned on windows 8 compatibility and i forgot to turned it off after installing the Firefox-one.

Now it working fine. 


Mark
