### ISSUE TITLE
Floorp Browser compatibility

### ISSUE THREAD

**Issue by InterstellarOne** [Godiesc/firefox-one#13]
Floorp Browser is a Firefox fork with a built-in sidebar, similar in implementation to opera. Would you be able to look into adding this as an option in the theme? I think it would make the experience a lot closer to opera.

**Comment by Godiesc** [comment]
hi,
I'm a Firefox user and for that I made this theme, the base theme works on that fork, and the "Extra" features looks good or all the theme doesn't work at all?

**Comment by Godiesc** [comment]
@InterstellarOne  I created the theme for floorp, you can tested from here: https://github.com/Godiesc/floorp-one
