### ISSUE TITLE
new tab page glitching using autoscroll

### ISSUE THREAD

**Issue by Midnight0507** [Godiesc/firefox-one#16]
![issue](https://github.com/Godiesc/firefox-one/assets/110766220/d252a2ae-7227-4f4d-9181-15059c3e70a4)

**Comment by Godiesc** [comment]
hi, for now the bug isn't solvable. thanks for the report.

**Comment by TriDEntApollO** [comment]
I cannot replicate this issue can you provide bit more details

**Comment by Godiesc** [comment]
I updated the code to solve this issue, for now the fix you can test it downloading the theme from `code -> download zip`, was tested in Firefox Beta and will be release in the next version of the theme when Firefox v.130 arrives.
