### ISSUE TITLE
Tabs UI improvement idea

### ISSUE THREAD

**Issue by SunRizzze** [Godiesc/firefox-one#22]
![image](https://github.com/Godiesc/firefox-one/assets/88379879/cf3fedfc-f9c8-448d-9113-3e3081d3a5c6)

Little improvement idea
add space between tabs

**Comment by Godiesc** [comment]
hi, I made the theme inspired in Opera-One and the tabs looks without space in that browser. I don't know if I will make that change.

**Comment by SunRizzze** [comment]
> hi, I made the theme inspired in Opera-One and the tabs looks without space in that browser. I don't know if I will make that change.
> 
> Edit: try this code in your `one_tricks.css` if you want to add that space:
> 
> ```
> /* Borde entre pestañas */
> 
> .tabbrowser-tab {
>     padding-inline: 4px !important;
> }
> ```

![image](https://github.com/Godiesc/firefox-one/assets/88379879/147d36bd-210c-433b-b99a-99bb3054f32b)
perfect

**Comment by SunRizzze** [comment]
> hi, I made the theme inspired in Opera-One and the tabs looks without space in that browser. I don't know if I will make that change.
> 
> Edit: try this code in your `one_tricks.css` if you want to add that space:
> 
> ```
> /* Borde entre pestañas */
> 
> .tabbrowser-tab {
>     padding-inline: 4px !important;
> }
> ```

![image](https://github.com/Godiesc/firefox-one/assets/88379879/27a48ca3-f92f-4e3a-8c23-5e1b1f70455c)

perfect
