### ISSUE TITLE
Feature Request adding shortcuts to the sidebar

### ISSUE THREAD

**Issue by gun4qmm7h** [Godiesc/firefox-one#23]
Is there a way that we can add the home shortcuts to the sidebar as somewhat shown in the image
![2024-01-25_20-01](https://github.com/Godiesc/firefox-one/assets/74073434/127b1941-cc0e-42bb-84eb-23ee56b6eefc)

**Comment by Godiesc** [comment]
hi, you can bookmark that sites and save them, I see your bookmark folders in that bar, you can bookmark your pinned sites and save them outside any folder.
