### ISSUE TITLE
Orange line above address bar toolbar(?)

### ISSUE THREAD

**Issue by Xeiv** [Godiesc/firefox-one#24]
Hello, I just opened firefox today and there was this line above the address bar toolbar(?), This wasn't there before and I was wondering if this was an intended change or something to do with a firefox update 👀
I'm using firefoxone.tree_tabs_style and firefoxone.style_without_leftsidebar with the Opera GX Ember Orange theme.

![image](https://github.com/Godiesc/firefox-one/assets/25398298/d59a498d-892b-4a9b-8369-a5da00b5b1f8)

**Comment by Godiesc** [comment]
hi, for now I still didn't release a new version of the theme, but that problem was solved, just download from code -> download zip. I hope is the only problem, I will test it this days. Thanks for the report.

**Comment by Xeiv** [comment]
Alright thank you very much

**Comment by Godiesc** [comment]
solved with the latest update. Thanks for the report.
