### ISSUE TITLE
Menu popout for bookmark folders cover the rest of the bookmarks bar.

### ISSUE THREAD

**Issue by mantacid** [Godiesc/firefox-one#25]
Just as the title says, the popout menus for bookmark folders block the other bookmarks below them. I've tried to move the menus with a CSS transform, but that still didn't let me preview folder contents by hovering. I've tried `position: relative`, I've tried `margin-left: 20px;`, all to no avail.

**Comment by Godiesc** [comment]
hi, try to upload a screenshot of your problem, is the easiest way to see the issue. If I understand you, you want to move the bookmarks menu popup a little to the right, put this code to `one_tricks.css`

```
#PlacesToolbarItems > .bookmark-item >  menupopup, #OtherBookmarks #OtherBookmarksPopup {
        margin-inline-start: calc(var(--padding-left-tab) - 0px) !important;
        margin-top: -56px  !important;
    }
```

**Comment by mantacid** [comment]
![image](https://github.com/Godiesc/firefox-one/assets/123284210/c2755a62-f199-43c4-9534-f9969f7e9f9f)

There are two other folders under this pop out that I want to be able to see.

**Comment by Godiesc** [comment]
I gave you the code to fix that. 👍

**Comment by mantacid** [comment]
You did? When? the code earlier in this issue addressed the "other bookmarks" pop-out, right? When I attempted to solve the problem myself, I used the browser debugger and found the selector to be `toolbarbutton.bookmark-item[type="menu"] > menupopup.toolbar-menumenupopup`

**Comment by Godiesc** [comment]
there are 2 selectors in the code I gave you, one for normal bookmark folders and the other for the "other bookmarks" folder.

**Comment by mantacid** [comment]
That makes sense. I didn't see the comma there.

**Comment by Godiesc** [comment]
I added this change in the last release of the theme. 👍
