### ISSUE TITLE
Bookmarks not updating to sidebar apps

### ISSUE THREAD

**Issue by mark-boute** [Godiesc/firefox-one#28]
Very nice, thanks for making this!
On Windows 11 my bookmarks seem to be displayed on the left side, instead of the installed sidebar extensions. Is this expected behavior, or did I mess something up?

I'll be testing this on my Arch/Hyprland (Wayland) install in a bit.

![image](https://github.com/Godiesc/firefox-one/assets/33718602/11635ab3-8339-4b60-ac75-0262a45064ff)

**Comment by Godiesc** [comment]
hi,
you should move your extensions buttons to the left-sidebar manually in '[customization mode](https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars)', they don't move automatically to there.
