### ISSUE TITLE
[Visual layout issue] Vertical bookmarks bar overlaps horizontal Tab + main bar

### ISSUE THREAD

**Issue by vctr00** [Godiesc/firefox-one#3]
Bookmarks bar interferes with elements on the top left side of the browser window. Installed theme per instructions. Is this a configuration issue I missed? CSS issue? Appreciate the work you've done here. Thank you.

Windows 10 22H2. Firefox Nightly 117.0a1 (2023-07-25)

<img width="113" alt="Screenshot 2023-07-25 131330" src="https://github.com/Godiesc/firefox-one/assets/140540491/ec6cf49c-9767-41af-8218-b5e612dca104">

**Comment by Godiesc** [comment]
hi,
Firefox nightly is the alpha channel and has a lot of changes in the interface, I usually work on beta version to make the theme, right now with Firefox 116 that will arrive to stable in one week all the theme looks great, when beta channel goes to v.117 that bugs will appear, and I will fix them in that time.

**Comment by vctr00** [comment]
Confirming that this visual bug does not appear in main FF release.

**Comment by Godiesc** [comment]
Solved with the latest update of the files.
