### ISSUE TITLE
the left sidebar

### ISSUE THREAD

**Issue by CiannieTheBottom** [Godiesc/firefox-one#30]
the left sidebar, how do I add the extentions there? it's not explaind anythwere, and I have no idea how to do it :cccccccc

**Comment by Godiesc** [comment]
hi, that is part of the basic handling of Firefox, you should first 'pin to the toolbar' the extensions from the 'unified extension button' and after that in 'customization mode' you move them to the left-sidebar.

![Sin título](https://github.com/Godiesc/firefox-one/assets/22057609/589901ee-8875-4e37-b820-91d825d87edf)

**Comment by ElijahHW** [comment]
I still dont understand how to get the left side bar... It's nto very clear how to do this.

**Comment by Godiesc** [comment]
@ElijahHW  for default the left-sidebar is enable, for this bar I use the bookmarks-bar, so be sure to have that bar on.

![imagen](https://github.com/Godiesc/firefox-one/assets/22057609/e19b12b0-5fe3-4a7f-bc32-60c805baf067)
