### ISSUE TITLE
Tab names are misaligned within tabs, website area background not respected

### ISSUE THREAD

**Issue by ptrwrbl** [Godiesc/firefox-one#32]
## Current behavior
After updating Firefox Developer Edition, top part of the window became misaligned — tabs and window control became slightly shifted towards the top.

Additionally, I'm not sure if my browser properly respects background color set by FirefoxOne-related theme:
- background behind opened website area reset to Firefox' default, making it almost the same as sidebar
- background behind omnibox looks like it is intended to be transparent but it isn't

### Context (Environment)
Firefox Developer Edition 126.0b4 on Windows 11 23H2

### Screenshots
![Bookmarks bar disabled](https://github.com/Godiesc/firefox-one/assets/14293502/b32ec986-5b0e-4512-9755-447b3c543862)
![Bookmarks bar enabled](https://github.com/Godiesc/firefox-one/assets/14293502/775c0b51-bfdb-48b9-9b3a-dea6724e75eb)

**Comment by Godiesc** [comment]
hi,
Thanks for the report, I updated some files (one_optional-features.css, one_root.css, one_tabs-bar.css) to solve the problems, If you find another issue, please report it, thanks.
