### ISSUE TITLE
main window edge corner won't work on some websites

### ISSUE THREAD

**Issue by l2eused** [Godiesc/firefox-one#33]
e.g [opera website](https://www.opera.com/)

in corners it overlap. so I think it should be fix

ref for worked edge css style: [edge-frfox](https://github.com/bmFtZQ/edge-frfox/blob/main/chrome/global/browser.css)

**Comment by Godiesc** [comment]
hi,
Please share a screenshot with the issue you are experiment, this is the page you shared and for me it looks just right.

![imagen](https://github.com/Godiesc/firefox-one/assets/22057609/a56b0d1f-87b1-49c4-b0d4-e905310ee895)

**Comment by Godiesc** [comment]
don't forget to copy too the user.js to your profile folder. Unfortunately I can't reproduce your issue, I tested in stable and beta version, I only experiment that the rounded border becomes less rounded when scrolling down, but not the floating pixel. maybe there is another factor causing the problem but seems I can't fix it cause I don't have it.

![imagen](https://github.com/Godiesc/firefox-one/assets/22057609/49ed1c9a-26b7-4ea1-abaf-b2d7dfb76fe4)

**Comment by Godiesc** [comment]
hi @l2eused I updated the code and made some changes in the way that border display, maybe that solve this issue, I tested in Firefox beta and hope Firefox Stable don't have any issue, you can test it from `code->download zip`.
