### ISSUE TITLE
Workspaces do not work/appear 

### ISSUE THREAD

**Issue by NightHunter27** [Godiesc/firefox-one#34]
I am unable to make the Workspaces (like in Opera) appear at all. I see in the screenshots that they are there, but whatever I do, I cannot make them appear. 
![image_2024-06-17_135547816](https://github.com/Godiesc/firefox-one/assets/5645735/e75f7edd-c341-4fce-bac7-862d56c23a34)

And the other social media apps, while not needed, when I do install them separately, they go into the sidebar app rather than the actual sidebar. 
![image](https://github.com/Godiesc/firefox-one/assets/5645735/562fd9c9-1660-4012-af49-565594d7ab01)

**Comment by Godiesc** [comment]
hi,
The Workspaces (like in Opera) is not possible in Firefox, I use the [Simple-tab-groups](https://addons.mozilla.org/firefox/addon/simple-tab-groups/) extension and just put in the left-sidebar.

all the extensions you want in the left-sidebar first you should pin to the toolbar from the Unified Extension Button:

![imagen](https://github.com/Godiesc/firefox-one/assets/22057609/c0a595e1-a2b7-498a-bbc3-385a444b5ac3)

after that you can move the extension to the left-sidebar in customization mode:

![imagen](https://github.com/Godiesc/firefox-one/assets/22057609/1eb3f511-d481-4b01-af24-2e704d6b1b80)

**Comment by NightHunter27** [comment]
Thank you for the fast reply. The tab groups will have to do for the time being. 
Thanks again.
