### ISSUE TITLE
Firefox menu list overlaps the menu icon

### ISSUE THREAD

**Issue by TriDEntApollO** [Godiesc/firefox-one#35]
![image](https://github.com/Godiesc/firefox-one/assets/68052236/74b49ad4-b53b-44f3-bff3-c6658976c117)

Here in the image you can see the firefox menu logo and text is in the wrong position and the list renders above the logo

**Comment by Godiesc** [comment]
hi, thanks for the report, I will solve it soon, but in linux sadly if you use Wayland it display wrong, different than X11.

**Comment by TriDEntApollO** [comment]
Sadly i am using wayland

**Comment by Godiesc** [comment]
if wayland is the replace of X11 and wayland is more common I will try to make it compatible with that and not X11.

**Comment by TriDEntApollO** [comment]
> if wayland is the replace of X11 and wayland is more common I will try to make it compatible with that and not X11.

Thats actually great. More people are actaully moving to wayland form X11 and wayland support is getting betterr and better every day

**Comment by TriDEntApollO** [comment]
Update

I noticed that this issue only happens in full screen

**Comment by Godiesc** [comment]
the code was updated to solve it. now the hamburger menu don't display like in Windows OS to don't have issues with the difference between X11 and Wayland.

**Comment by TriDEntApollO** [comment]
Hey thanks, i really like this theme and wanted to stick to this so fixing these bugs are really helpful. I will test them out and let you know.

**Comment by TriDEntApollO** [comment]
So, I tested this out and and yes the problem is no more there in the latest config. Thank you and i am closing the issue.
