### ISSUE TITLE
Window control buttons backgroud doesn't fade after losing focus form hover in some cases

### ISSUE THREAD

**Issue by TriDEntApollO** [Godiesc/firefox-one#37]
https://github.com/Godiesc/firefox-one/assets/68052236/690fe910-b17c-4d4b-bdcc-c3ef0b3de490

In the video you can see when the cusror hover in between or over multiple buttons only the last button to loose cusor hover changes it background to transparent

**Comment by Godiesc** [comment]
hi,
I updated the code to solve this problem, I tested in Firefox Beta and I will release the changes in 15 days, you can test it from code->download zip, maybe in Firefox Stable works fine. A new way to display the wallpaper in newtab page was added using the new Firefox feature and you can active it with this:

`browser.newtabpage.activity-stream.newtabWallpapers.enabled` to `true`

**Comment by TriDEntApollO** [comment]
So the issue is indeed fixed in the latest commit and everything works as expected.

One unrelated question tho out of curiosity that in the preview image how did you get those colorful bars before the pinned homepage tabs

![image](https://github.com/Godiesc/firefox-one/assets/68052236/122251df-5bf5-4ef5-8e90-48d53c1b702c)


And thanks for your time and effort

**Comment by Godiesc** [comment]
![imagen](https://github.com/Godiesc/firefox-one/assets/22057609/1142439c-896f-4d40-8d4d-723e77cdd3b2)

the container tabs? you create them from right clic on the NewTab button:

![Sin título](https://github.com/Godiesc/firefox-one/assets/22057609/beeffd42-5ae1-401e-a0d7-59155d9d57d9)

**Comment by TriDEntApollO** [comment]
> ![imagen](https://private-user-images.githubusercontent.com/22057609/343269353-1142439c-896f-4d40-8d4d-723e77cdd3b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MzA2ODcsIm5iZiI6MTcxOTQzMDM4NywicGF0aCI6Ii8yMjA1NzYwOS8zNDMyNjkzNTMtMTE0MjQzOWMtODk2Zi00ZDQwLThkNGQtNzIzZTc3Y2RkM2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE5MzMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNGIyNjY2MWVmM2Y0MjA1MzUxYTYyMGQ1ZTMwM2FiZGM0NWJlOGRkYmE1YzY5NGFiZDFlNGY2Y2YzMWI1MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dkbG-vbZWxCBRsQHlW-9Tz0_ut_af_SiwJEXunKa11A)
> 
> the container tabs? you create them from right clic on the NewTab button:
> 
> ![Sin título](https://private-user-images.githubusercontent.com/22057609/343271557-beeffd42-5ae1-401e-a0d7-59155d9d57d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MzA2ODcsIm5iZiI6MTcxOTQzMDM4NywicGF0aCI6Ii8yMjA1NzYwOS8zNDMyNzE1NTctYmVlZmZkNDItNWFlMS00MDFlLWEwZDctNTkxNTVkOWQ1N2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDE5MzMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNjc2MWRhODk1ZWRmNzNmM2RjMmZhOTVkZjNiMjkwMTMxYTE0YzY1OWVmMDRiM2E1NzFiNzdiMmE1OTllNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EDvat4_mskqPrDNwL3o892Blb1an2IOhzQGb8JiCcDI)

Dumb me, thank you for the info
