### ISSUE TITLE
Bookmarks bar doesnt show up on Linux

### ISSUE THREAD

**Issue by EiskaffeeVRC** [Godiesc/firefox-one#4]
The bookmarks bar does not show up on Linux

Distro: Arch Linux
DE: KDE Plasma
![image](https://github.com/Godiesc/firefox-one/assets/7049718/73ef96d0-54e8-4fcd-a1e9-df40c0190c4c)

**Comment by Godiesc** [comment]
Hi,
You should have your bookmark-bar in "always show". Right clic in the toolbar > bookmark toolbar > always show
