### ISSUE TITLE
Right Click Menu Not Rendering Correctly in Dev 131.0b2

### ISSUE THREAD

**Issue by Karl-Larson** [Godiesc/firefox-one#42]
A second border has showed up in the right click menu of the latest Developer version.

I have tried pulling the latest files from the main branch.

![2024-09-05_17-33-57](https://github.com/user-attachments/assets/8f725491-fe9f-4b20-82e9-b3e8cb227f32)

**Comment by Godiesc** [comment]
hi,
thanks for the bug report, I updated the `one_arropanel.css` file to solve this issue.
