### ISSUE TITLE
How can i add custom wallpapers here

### ISSUE THREAD

**Issue by ravisrma** [Godiesc/firefox-one#43]
![image](https://github.com/user-attachments/assets/c4f3b885-e4b7-40a0-8c4c-48e098580983)

**Comment by Godiesc** [comment]
hi, this theme has set 'Photographs' category with images from `chrome/images` folder, you can replace them with your own images changing to the same names or read the github main page to know the file to edit.

**Comment by ravisrma** [comment]
in this folder all are svg not able to see photograps folder

**Comment by Godiesc** [comment]
my mistake, the folder chrome/images was replaced some versions ago, be sure to download the latest version of the theme from the 'Releases' section, and the wallpaper images are into `chrome/newtab` folder
