### ISSUE TITLE
Tab Center Reborn Sitting Above Wepage Content in Dev 132.0b3

### ISSUE THREAD

**Issue by Karl-Larson** [Godiesc/firefox-one#46]
After the latest update, Tab Center Reborn is now sitting over webpage content when not expanded.
I do believe this issue may affect FirefoxGX as well.

![FortniteClient-Win64-Shipping_2024-10-05_20-23-59](https://github.com/user-attachments/assets/73c15387-c3af-4486-bf20-b213781eeee1)

Let me know if there is any other info I can provide.

**Comment by Godiesc** [comment]
hi, thanks for the issue report, right now there is no problem with stable version, In beta/developer the ID for the container of web-content changed its name so maybe the solution will be easy just replacing the name, I will checked.

**Comment by Godiesc** [comment]
I updated the `one_tree-tabs.css` file to solve the problem, if there is another issue pls report again. 🤍
