### ISSUE TITLE
Tab Bar Overlaps Website

### ISSUE THREAD

**Issue by sup3rm4nny** [Godiesc/firefox-one#47]
The latest Firefox update (132.0) has caused the Tab Bar to overlap the left most part of the website. If you turn off the Tab Center Reborn extension the entire website will appear. But once you turn it back on the webpage does not shift to the right for the Tab Bar to appear. Instead it remains in the same place and the Tab Bar appears overlapping it.

**Comment by Godiesc** [comment]
hi, the problem persist if you download the file from the main repository(code > download zip) ?

**Comment by sup3rm4nny** [comment]
The issue is resolved with the update you released. Thank you!
