### ISSUE TITLE
Forefox Dev 133.0b4 - Tab Center Reborn / Windows Controls

### ISSUE THREAD

**Issue by Karl-Larson** [Godiesc/firefox-one#49]
Tab Center Reborn and the left side bar have an empty space between the contents and webpage:

![TCR](https://github.com/user-attachments/assets/f0a7b904-8351-4378-9a07-9babb63c2ee2)

Windows window controls have gone missing as well:
![Window_Controls](https://github.com/user-attachments/assets/e14e4e4a-6d19-4496-8fb0-acbed07acecd)

Let me know if there is any other info I can provide.

**Comment by Godiesc** [comment]
hi,
sorry for the late answer. first of all if you have any issue pls be sure to download again the latest version of the theme that works fine with the release version of Firefox. Maybe for beta you could see some issues if Firefox change the IDS or classes and an update for me is needed, but I release recently the v.134 that should works just fine.
Are you download the latest code and the problem persist?

**Comment by Karl-Larson** [comment]
I have downloaded the latest released version (132.0.)
I should have clarified this is Firefox Dev/Beta. (I have updated the title to clarify this.)

The issue does still persist as of 133.0b6.

**Comment by Godiesc** [comment]
Thanks for the report, I will work on it in a near future, in my country there are a lot of blackouts and I can't work properly.
I will test the theme in the latest beta version that seems to be 133.0b6.

**Comment by Karl-Larson** [comment]
Take your time!

Just wanted to make you aware of the issue.

**Comment by Karl-Larson** [comment]
Figured out that the empty space between TCR and web page content was due to the sidebar.revamp config.

**Comment by Godiesc** [comment]
thanks for the report, I updated the files to solve various issues with this new Firefox version, would be great if you can test it if you use windows (only tested it on windows). The css style for TabCenterReborn was updated too so you will need to update it too.

**Comment by Karl-Larson** [comment]
Just got everything updated and it all seems to be working!

I'll keep an eye out for any other issues!
