### ISSUE TITLE
Close tab button on nightly bigger than it should

### ISSUE THREAD

**Issue by SantiGLI** [Godiesc/firefox-one#5]
Hello, just like I said on the title, the close tab button on Nightly is bigger than it should be.

![image](https://github.com/Godiesc/firefox-one/assets/110741430/10da5d20-6e0f-4540-96a9-6b0bc1b23763)

I know you're gonna fix it when 117 is in Beta but I just wanted to let you know.

Love Firefox One btw

**Comment by Godiesc** [comment]
in a few hours I will release the stable version for v.116 and will fix that for nightly, for sure will arrives that change in beta in some days.

**Comment by Godiesc** [comment]
Solved with the latest update of the files.
