### ISSUE TITLE
Tab Center Wide

### ISSUE THREAD

**Issue by sup3rm4nny** [Godiesc/firefox-one#50]
I saw that you release an update for the theme and it did fix the issue that prevented the Tab Center Tree not being able to open. However, now with this new update when Tab Center Tree is minimized it is showing more than just the website icons. I attached a screenshot.

![Screenshot 2024-11-26 132252](https://github.com/user-attachments/assets/0984080d-155e-4e8f-ad49-35ddc6056834)

**Comment by sup3rm4nny** [comment]
Nevermind I fixed it. I just recopied the Tab Center Reborn CSS into the Custom Stylesheet.

**Comment by Godiesc** [comment]
hi,
the css for the extension was updated too, I added that info in the release notes for future users that could have that problem, thanks for the report.
