### ISSUE TITLE
Fallo con la extensión de Tab Center Reborn

### ISSUE THREAD

**Issue by MuerteRoja** [Godiesc/firefox-one#51]
Hola Godiesc, ya hemos hablado antes, no sé si todavía a día de hoy te acordás de mí, bueno, la cosa es que con la última actualización que subiste del tema, la versión 133 la extensión me falla un poco, en lo referente a que, como poder ver la frase de “Abrir una nueva pestaña” no se me llega a ocultar completamente, me sigue apareciendo la palabra “Ab” no sé si podrías arreglar eso, saludos, espero que todo te esté yendo bien.
![Captura de pantalla 2024-12-10 215142](https://github.com/user-attachments/assets/844d9220-0a38-4762-9df0-0c190f91777d)

**Comment by Godiesc** [comment]
hi,
con la ultima versión del tema también actualicé el css para la extensión, si lo hiciste?, si no pues debes hacerlo.

**Comment by MuerteRoja** [comment]
> hi, con la ultima versión del tema también actualicé el css para la extensión, si lo hiciste?, si no pues debes hacerlo. PD: Nunca pruebo el tema para librewolf o waterfox, no recuerdo cual tienes, pero con Firefox 133 no vi ningún problema.

Lo hice, actualicé el css, pero aun así parece no funcionar, da igual, este fallo no significa un mayor problema para mi
