### ISSUE TITLE
Width issue with Sidebery extension.

### ISSUE THREAD

**Issue by vogonwann** [Godiesc/firefox-one#52]
Hello,

I'm pretty sure that this was OK in previous version, but now I have an issue with the sidebery panel which cannot be resized, so it is more or less useless.

![slika](https://github.com/user-attachments/assets/30a9626d-1732-4e95-a95f-7c90d59f1d4c)

**Comment by Godiesc** [comment]
hi,
thanks for the report, I updated the file: `chrome/components/one_tree-tabs.css` to solve the problem, you should download the theme from the button: `code -> download zip.`

**Comment by vogonwann** [comment]
Thanks for the quick fix. Works like a charm! Cheers!
