### ISSUE TITLE
1. Firefox Logo blurry gradient background 2. 

### ISSUE THREAD

**Issue by JVariance** [Godiesc/firefox-one#6]
1. The Firefox Logo has a "blurry gradient" background. I could manually fix this, but wanted to get your input first.
![grafik](https://github.com/Godiesc/firefox-one/assets/62245444/14d613d1-2f94-410f-b9a8-09ed4b694a2c)

2. I installed 'Panorama Tab Groups', but I don't get the tab groups like in your example image.
![grafik](https://github.com/Godiesc/firefox-one/assets/62245444/c3816d1e-6a1f-4dc7-86af-ee02780e0e92)

**Comment by JVariance** [comment]
3. Could you support the 'Simple Tab Groups' add-on?
https://addons.mozilla.org/de/firefox/addon/simple-tab-groups/

**Comment by Godiesc** [comment]
hi,
> 1. The Firefox Logo has a "blurry gradient" background. I could manually fix this, but wanted to get your input first.

In a few days with the next update for firefox I'll upload a new version of this theme (Firefox-one) and that "blurry gradient" background I deleted it. If you want now you can download the theme from: Code -> download zip in github page.

>     2. I installed 'Panorama Tab Groups', but I don't get the tab groups like in your example image.

You should put the extension icon in that sidebar, if not, the icon just show the original extension icon, let me see how looks the icon in that left-sidebar to know how it looks.

> 3. Could you support the 'Simple Tab Groups' add-on?

I could added if you want, I need to install that extension and search for the id and add that in the code.

> 4. The menu has this grainy background. Should it be like this?

I did it on purpose., I think looks better that a solid white or dark, you can delete the image `urlbar-noise-light.png` form `chrome/images` if you don't like it.

**Comment by JVariance** [comment]
Thanks!

The id of Simple Tab Groups is 'simple-tab-groups@drive4ik'

**Comment by JVariance** [comment]
> Thanks!
> 
> The id of Simple Tab Groups is 'simple-tab-groups@drive4ik'

There is also an internal uuid, but that's unique per device, right?

**Comment by Godiesc** [comment]
I suggest you to update the theme(Firefox-one) when the next release of Firefox arrive cause there are little changes and still I'm updating the theme.
And for your extension I will tested in a moment, I hope my other extension don't make some conflict and loose my tabs jeje

**Comment by JVariance** [comment]
Basically I like the noisy background, but for my taste it's a bit too intense. I'll try to lower the opacity.

**Comment by JVariance** [comment]
And thanks for making this!
I really love the look of Opera One and also switched to it from Firefox, because it's very conveniant with tab islands etc.. Though I would rather like to use Firefox..

**Comment by Godiesc** [comment]
![imagen](https://github.com/Godiesc/firefox-one/assets/22057609/40c1b9df-8ab1-4a0a-bd20-ba925811c680)
 
I updated the files for your extension, one is for panorama tabs group and the other for simple tab groups, just for clarify, the Star Icon in my screenshot is the "bookmarks menu" button, not for other group like Opera feature.

**Comment by JVariance** [comment]
> ![imagen](https://user-images.githubusercontent.com/22057609/263059306-40c1b9df-8ab1-4a0a-bd20-ba925811c680.png)
> 
> I updated the files for your extension, one is for panorama tabs group and the other for simple tab groups, just for clarify, the Star Icon in my screenshot is the "bookmarks menu" button, not for other group like Opera feature.

Amazing, thanks!
