### ISSUE TITLE
Layout and color issues on 119.0b3

### ISSUE THREAD

**Issue by agent-seed** [Godiesc/firefox-one#8]
The layout is broken on 119.0b3

**Comment by agent-seed** [comment]
![image](https://github.com/Godiesc/firefox-one/assets/92690644/b0d099c5-52cf-4ba3-8bdb-96bb1467d0d8)
![image](https://github.com/Godiesc/firefox-one/assets/92690644/0f0fab6c-fcee-4f67-b728-072a94207086)
The side bar is interacting weirdly with the top bar, and icon colors are black in dark mode

**Comment by Godiesc** [comment]
hi,
Are you using a compatible theme? I've saw that problems when you use an incomplete themes.

**Comment by agent-seed** [comment]
Ah that seems to be the problem, thank you

**Comment by agent-seed** [comment]
Using [this theme](https://addons.mozilla.org/en-US/firefox/addon/beautiful-gx-fantasy/) fixed it

**Comment by Godiesc** [comment]
if you were using that "automatic theme" you should try the default dark theme, or others [of my authorship](https://addons.mozilla.org/es/firefox/user/7024772/)

![imagen](https://github.com/Godiesc/firefox-one/assets/22057609/b9b59ed3-d097-48d0-b22a-31093444edb5)
