### ISSUE TITLE
Firefox logo and watermark not showing

### ISSUE THREAD

**Issue by gun4qmm7h** [Godiesc/firefox-one#9]
![image](https://github.com/Godiesc/firefox-one/assets/74073434/fc87c547-e22a-40e2-9011-6ad1d5a9ec18)
![image](https://github.com/Godiesc/firefox-one/assets/74073434/c91df8aa-ac59-4e6f-82af-6cc4b5b9c249)
if this is not a mistake can you make it so you can add or remove it?

**Comment by Godiesc** [comment]
hi,
in the [github description I wrote some important info](https://github.com/Godiesc/firefox-one#personalizar---customize) like the one you want. The lines for that are  from 42 to 46.

![imagen](https://github.com/Godiesc/firefox-one/assets/22057609/40dea1c8-41e6-4d3b-86d7-4615b3e50117)

**Comment by gun4qmm7h** [comment]
Sorry. I'm a bit slow at reading

**Comment by Godiesc** [comment]
if you want the original logo or wordmark you should do other steps.
